//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraPdfBuzonE
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class NamingException
    {
        
        private object resolvedObjField;
        
        private string explanationField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object resolvedObj
        {
            get
            {
                return this.resolvedObjField;
            }
            set
            {
                this.resolvedObjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string explanation
        {
            get
            {
                return this.explanationField;
            }
            set
            {
                this.explanationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class setAsyncBinnacleResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class asyncBinnacle
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class setAsyncBinnacle
    {
        
        private asyncBinnacle arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public asyncBinnacle arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFEfosResponse
    {
        
        private revisaXmlValidoSATPDFEfosResponseReturn returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public revisaXmlValidoSATPDFEfosResponseReturn @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFEfosResponseReturn
    {
        
        private ejecucionservicio ejecucionservicioField;
        
        private respuestageneracionpdf respuestageneracionpdfField;
        
        private respuestaconsultacfdi respuestaconsultacfdiField;
        
        private respuestavalidacfdi respuestavalidacfdiField;
        
        private string uuidcfdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ejecucion-servicio", Namespace="modelo", Order=0)]
        public ejecucionservicio ejecucionservicio
        {
            get
            {
                return this.ejecucionservicioField;
            }
            set
            {
                this.ejecucionservicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-generacionpdf", Namespace="modelo", Order=1)]
        public respuestageneracionpdf respuestageneracionpdf
        {
            get
            {
                return this.respuestageneracionpdfField;
            }
            set
            {
                this.respuestageneracionpdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-consulta-cfdi", Namespace="modelo", Order=2)]
        public respuestaconsultacfdi respuestaconsultacfdi
        {
            get
            {
                return this.respuestaconsultacfdiField;
            }
            set
            {
                this.respuestaconsultacfdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-valida-cfdi", Namespace="modelo", Order=3)]
        public respuestavalidacfdi respuestavalidacfdi
        {
            get
            {
                return this.respuestavalidacfdiField;
            }
            set
            {
                this.respuestavalidacfdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("uuid-cfdi")]
        public string uuidcfdi
        {
            get
            {
                return this.uuidcfdiField;
            }
            set
            {
                this.uuidcfdiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelo")]
    public partial class ejecucionservicio
    {
        
        private string claveField;
        
        private string descripcionField;
        
        private string detalleField;
        
        private string foliosbitacoraField;
        
        private string fechaejecucionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("folios-bitacora")]
        public string foliosbitacora
        {
            get
            {
                return this.foliosbitacoraField;
            }
            set
            {
                this.foliosbitacoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("fecha-ejecucion")]
        public string fechaejecucion
        {
            get
            {
                return this.fechaejecucionField;
            }
            set
            {
                this.fechaejecucionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelo")]
    public partial class respuestageneracionpdf
    {
        
        private ejecucionservicio ejecucionservicioField;
        
        private pdf pdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ejecucion-servicio", Order=0)]
        public ejecucionservicio ejecucionservicio
        {
            get
            {
                return this.ejecucionservicioField;
            }
            set
            {
                this.ejecucionservicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public pdf pdf
        {
            get
            {
                return this.pdfField;
            }
            set
            {
                this.pdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelo")]
    public partial class pdf
    {
        
        private string documentobase64Field;
        
        private string xmloriginalbase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("documento-base64")]
        public string documentobase64
        {
            get
            {
                return this.documentobase64Field;
            }
            set
            {
                this.documentobase64Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xml-original-base64")]
        public string xmloriginalbase64
        {
            get
            {
                return this.xmloriginalbase64Field;
            }
            set
            {
                this.xmloriginalbase64Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelo")]
    public partial class respuestaconsultacfdi
    {
        
        private ejecucionservicio ejecucionservicioField;
        
        private datosAdicionalCancelacion datosAdicionalCancelacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ejecucion-servicio", Order=0)]
        public ejecucionservicio ejecucionservicio
        {
            get
            {
                return this.ejecucionservicioField;
            }
            set
            {
                this.ejecucionservicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosAdicional-Cancelacion", Order=1)]
        public datosAdicionalCancelacion datosAdicionalCancelacion
        {
            get
            {
                return this.datosAdicionalCancelacionField;
            }
            set
            {
                this.datosAdicionalCancelacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelo")]
    public partial class datosAdicionalCancelacion
    {
        
        private string esCancelableField;
        
        private string estatusCancelacionField;
        
        private string validacionEFOSField;
        
        private string mensajeEFOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string esCancelable
        {
            get
            {
                return this.esCancelableField;
            }
            set
            {
                this.esCancelableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string estatusCancelacion
        {
            get
            {
                return this.estatusCancelacionField;
            }
            set
            {
                this.estatusCancelacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string validacionEFOS
        {
            get
            {
                return this.validacionEFOSField;
            }
            set
            {
                this.validacionEFOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mensajeEFOS
        {
            get
            {
                return this.mensajeEFOSField;
            }
            set
            {
                this.mensajeEFOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelo")]
    public partial class respuestavalidacfdi
    {
        
        private ejecucionservicio ejecucionservicioField;
        
        private xmlvalidado xmlvalidadoField;
        
        private detalleerrorError[] detalleerrorField;
        
        private string idrevisionbitacoraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ejecucion-servicio", Order=0)]
        public ejecucionservicio ejecucionservicio
        {
            get
            {
                return this.ejecucionservicioField;
            }
            set
            {
                this.ejecucionservicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("xml-validado", Order=1)]
        public xmlvalidado xmlvalidado
        {
            get
            {
                return this.xmlvalidadoField;
            }
            set
            {
                this.xmlvalidadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("detalle-error", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error")]
        public detalleerrorError[] detalleerror
        {
            get
            {
                return this.detalleerrorField;
            }
            set
            {
                this.detalleerrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("id-revision-bitacora")]
        public string idrevisionbitacora
        {
            get
            {
                return this.idrevisionbitacoraField;
            }
            set
            {
                this.idrevisionbitacoraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelo")]
    public partial class xmlvalidado
    {
        
        private string documentobase64Field;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("documento-base64")]
        public string documentobase64
        {
            get
            {
                return this.documentobase64Field;
            }
            set
            {
                this.documentobase64Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelo")]
    public partial class detalleerrorError
    {
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFEfos
    {
        
        private byte[] xmlField;
        
        private string usuarioField;
        
        private string passwordField;
        
        private string claveTipoPdfField;
        
        private bool bEjecutaValidacionField;
        
        private bool bRegresaXmlValidacionField;
        
        private bool bEjecutaConsultaField;
        
        private bool bEjecutaPdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string claveTipoPdf
        {
            get
            {
                return this.claveTipoPdfField;
            }
            set
            {
                this.claveTipoPdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool bEjecutaValidacion
        {
            get
            {
                return this.bEjecutaValidacionField;
            }
            set
            {
                this.bEjecutaValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool bRegresaXmlValidacion
        {
            get
            {
                return this.bRegresaXmlValidacionField;
            }
            set
            {
                this.bRegresaXmlValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool bEjecutaConsulta
        {
            get
            {
                return this.bEjecutaConsultaField;
            }
            set
            {
                this.bEjecutaConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool bEjecutaPdf
        {
            get
            {
                return this.bEjecutaPdfField;
            }
            set
            {
                this.bEjecutaPdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFResponse
    {
        
        private revisaXmlValidoSATPDFResponseReturn returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public revisaXmlValidoSATPDFResponseReturn @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFResponseReturn
    {
        
        private ejecucionservicio ejecucionservicioField;
        
        private respuestageneracionpdf respuestageneracionpdfField;
        
        private respuestaconsultacfdi respuestaconsultacfdiField;
        
        private respuestavalidacfdi respuestavalidacfdiField;
        
        private string uuidcfdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ejecucion-servicio", Namespace="modelo", Order=0)]
        public ejecucionservicio ejecucionservicio
        {
            get
            {
                return this.ejecucionservicioField;
            }
            set
            {
                this.ejecucionservicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-generacionpdf", Namespace="modelo", Order=1)]
        public respuestageneracionpdf respuestageneracionpdf
        {
            get
            {
                return this.respuestageneracionpdfField;
            }
            set
            {
                this.respuestageneracionpdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-consulta-cfdi", Namespace="modelo", Order=2)]
        public respuestaconsultacfdi respuestaconsultacfdi
        {
            get
            {
                return this.respuestaconsultacfdiField;
            }
            set
            {
                this.respuestaconsultacfdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-valida-cfdi", Namespace="modelo", Order=3)]
        public respuestavalidacfdi respuestavalidacfdi
        {
            get
            {
                return this.respuestavalidacfdiField;
            }
            set
            {
                this.respuestavalidacfdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("uuid-cfdi")]
        public string uuidcfdi
        {
            get
            {
                return this.uuidcfdiField;
            }
            set
            {
                this.uuidcfdiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDF
    {
        
        private byte[] xmlField;
        
        private string usuarioField;
        
        private string passwordField;
        
        private string claveTipoPdfField;
        
        private bool bEjecutaValidacionField;
        
        private bool bRegresaXmlValidacionField;
        
        private bool bEjecutaConsultaField;
        
        private bool bEjecutaPdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string claveTipoPdf
        {
            get
            {
                return this.claveTipoPdfField;
            }
            set
            {
                this.claveTipoPdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool bEjecutaValidacion
        {
            get
            {
                return this.bEjecutaValidacionField;
            }
            set
            {
                this.bEjecutaValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool bRegresaXmlValidacion
        {
            get
            {
                return this.bRegresaXmlValidacionField;
            }
            set
            {
                this.bRegresaXmlValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool bEjecutaConsulta
        {
            get
            {
                return this.bEjecutaConsultaField;
            }
            set
            {
                this.bEjecutaConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool bEjecutaPdf
        {
            get
            {
                return this.bEjecutaPdfField;
            }
            set
            {
                this.bEjecutaPdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFNoPasswordEfosResponse
    {
        
        private revisaXmlValidoSATPDFNoPasswordEfosResponseReturn returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public revisaXmlValidoSATPDFNoPasswordEfosResponseReturn @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFNoPasswordEfosResponseReturn
    {
        
        private ejecucionservicio ejecucionservicioField;
        
        private respuestageneracionpdf respuestageneracionpdfField;
        
        private respuestaconsultacfdi respuestaconsultacfdiField;
        
        private respuestavalidacfdi respuestavalidacfdiField;
        
        private string uuidcfdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ejecucion-servicio", Namespace="modelo", Order=0)]
        public ejecucionservicio ejecucionservicio
        {
            get
            {
                return this.ejecucionservicioField;
            }
            set
            {
                this.ejecucionservicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-generacionpdf", Namespace="modelo", Order=1)]
        public respuestageneracionpdf respuestageneracionpdf
        {
            get
            {
                return this.respuestageneracionpdfField;
            }
            set
            {
                this.respuestageneracionpdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-consulta-cfdi", Namespace="modelo", Order=2)]
        public respuestaconsultacfdi respuestaconsultacfdi
        {
            get
            {
                return this.respuestaconsultacfdiField;
            }
            set
            {
                this.respuestaconsultacfdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-valida-cfdi", Namespace="modelo", Order=3)]
        public respuestavalidacfdi respuestavalidacfdi
        {
            get
            {
                return this.respuestavalidacfdiField;
            }
            set
            {
                this.respuestavalidacfdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("uuid-cfdi")]
        public string uuidcfdi
        {
            get
            {
                return this.uuidcfdiField;
            }
            set
            {
                this.uuidcfdiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFNoPasswordEfos
    {
        
        private byte[] xmlField;
        
        private int idUsuarioField;
        
        private string claveTipoPdfField;
        
        private bool bEjecutaValidacionField;
        
        private bool bRegresaXmlValidacionField;
        
        private bool bEjecutaConsultaField;
        
        private bool bEjecutaPdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string claveTipoPdf
        {
            get
            {
                return this.claveTipoPdfField;
            }
            set
            {
                this.claveTipoPdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool bEjecutaValidacion
        {
            get
            {
                return this.bEjecutaValidacionField;
            }
            set
            {
                this.bEjecutaValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool bRegresaXmlValidacion
        {
            get
            {
                return this.bRegresaXmlValidacionField;
            }
            set
            {
                this.bRegresaXmlValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool bEjecutaConsulta
        {
            get
            {
                return this.bEjecutaConsultaField;
            }
            set
            {
                this.bEjecutaConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool bEjecutaPdf
        {
            get
            {
                return this.bEjecutaPdfField;
            }
            set
            {
                this.bEjecutaPdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFNoPasswordResponse
    {
        
        private revisaXmlValidoSATPDFNoPasswordResponseReturn returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public revisaXmlValidoSATPDFNoPasswordResponseReturn @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFNoPasswordResponseReturn
    {
        
        private ejecucionservicio ejecucionservicioField;
        
        private respuestageneracionpdf respuestageneracionpdfField;
        
        private respuestaconsultacfdi respuestaconsultacfdiField;
        
        private respuestavalidacfdi respuestavalidacfdiField;
        
        private string uuidcfdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ejecucion-servicio", Namespace="modelo", Order=0)]
        public ejecucionservicio ejecucionservicio
        {
            get
            {
                return this.ejecucionservicioField;
            }
            set
            {
                this.ejecucionservicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-generacionpdf", Namespace="modelo", Order=1)]
        public respuestageneracionpdf respuestageneracionpdf
        {
            get
            {
                return this.respuestageneracionpdfField;
            }
            set
            {
                this.respuestageneracionpdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-consulta-cfdi", Namespace="modelo", Order=2)]
        public respuestaconsultacfdi respuestaconsultacfdi
        {
            get
            {
                return this.respuestaconsultacfdiField;
            }
            set
            {
                this.respuestaconsultacfdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta-valida-cfdi", Namespace="modelo", Order=3)]
        public respuestavalidacfdi respuestavalidacfdi
        {
            get
            {
                return this.respuestavalidacfdiField;
            }
            set
            {
                this.respuestavalidacfdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("uuid-cfdi")]
        public string uuidcfdi
        {
            get
            {
                return this.uuidcfdiField;
            }
            set
            {
                this.uuidcfdiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class revisaXmlValidoSATPDFNoPassword
    {
        
        private byte[] xmlField;
        
        private int idUsuarioField;
        
        private string claveTipoPdfField;
        
        private bool bEjecutaValidacionField;
        
        private bool bRegresaXmlValidacionField;
        
        private bool bEjecutaConsultaField;
        
        private bool bEjecutaPdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string claveTipoPdf
        {
            get
            {
                return this.claveTipoPdfField;
            }
            set
            {
                this.claveTipoPdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool bEjecutaValidacion
        {
            get
            {
                return this.bEjecutaValidacionField;
            }
            set
            {
                this.bEjecutaValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool bRegresaXmlValidacion
        {
            get
            {
                return this.bRegresaXmlValidacionField;
            }
            set
            {
                this.bRegresaXmlValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool bEjecutaConsulta
        {
            get
            {
                return this.bEjecutaConsultaField;
            }
            set
            {
                this.bEjecutaConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool bEjecutaPdf
        {
            get
            {
                return this.bEjecutaPdfField;
            }
            set
            {
                this.bEjecutaPdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class initResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/")]
    public partial class init
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", ConfigurationName="GeneraPdfBuzonE.WsVerificaXmlRi")]
    public interface WsVerificaXmlRi
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GeneraPdfBuzonE.NamingException), Action="", Name="NamingException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacleResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacle))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPassword))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(initResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(init))]
        System.Threading.Tasks.Task initAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacleResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacle))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPassword))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(initResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(init))]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordResponse1> revisaXmlValidoSATPDFNoPasswordAsync(GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPassword1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacleResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacle))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPassword))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(initResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(init))]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordEfosResponse1> revisaXmlValidoSATPDFNoPasswordEfosAsync(GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordEfos1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GeneraPdfBuzonE.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacleResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacle))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPassword))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(initResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(init))]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFResponse1> revisaXmlValidoSATPDFAsync(GeneraPdfBuzonE.revisaXmlValidoSATPDF1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GeneraPdfBuzonE.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacleResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacle))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPassword))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(initResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(init))]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFEfosResponse1> revisaXmlValidoSATPDFEfosAsync(GeneraPdfBuzonE.revisaXmlValidoSATPDFEfos1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacleResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setAsyncBinnacle))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfosResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordEfos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPasswordResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(revisaXmlValidoSATPDFNoPassword))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(initResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(init))]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.setAsyncBinnacleResponse1> setAsyncBinnacleAsync(GeneraPdfBuzonE.setAsyncBinnacle1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revisaXmlValidoSATPDFNoPassword", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class revisaXmlValidoSATPDFNoPassword1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] xml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string claveTipoPdf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bRegresaXmlValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaConsulta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaPdf;
        
        public revisaXmlValidoSATPDFNoPassword1()
        {
        }
        
        public revisaXmlValidoSATPDFNoPassword1(byte[] xml, int idUsuario, string claveTipoPdf, bool bEjecutaValidacion, bool bRegresaXmlValidacion, bool bEjecutaConsulta, bool bEjecutaPdf)
        {
            this.xml = xml;
            this.idUsuario = idUsuario;
            this.claveTipoPdf = claveTipoPdf;
            this.bEjecutaValidacion = bEjecutaValidacion;
            this.bRegresaXmlValidacion = bRegresaXmlValidacion;
            this.bEjecutaConsulta = bEjecutaConsulta;
            this.bEjecutaPdf = bEjecutaPdf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revisaXmlValidoSATPDFNoPasswordResponse", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class revisaXmlValidoSATPDFNoPasswordResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordResponseReturn @return;
        
        public revisaXmlValidoSATPDFNoPasswordResponse1()
        {
        }
        
        public revisaXmlValidoSATPDFNoPasswordResponse1(GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordResponseReturn @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revisaXmlValidoSATPDFNoPasswordEfos", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class revisaXmlValidoSATPDFNoPasswordEfos1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] xml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string claveTipoPdf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bRegresaXmlValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaConsulta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaPdf;
        
        public revisaXmlValidoSATPDFNoPasswordEfos1()
        {
        }
        
        public revisaXmlValidoSATPDFNoPasswordEfos1(byte[] xml, int idUsuario, string claveTipoPdf, bool bEjecutaValidacion, bool bRegresaXmlValidacion, bool bEjecutaConsulta, bool bEjecutaPdf)
        {
            this.xml = xml;
            this.idUsuario = idUsuario;
            this.claveTipoPdf = claveTipoPdf;
            this.bEjecutaValidacion = bEjecutaValidacion;
            this.bRegresaXmlValidacion = bRegresaXmlValidacion;
            this.bEjecutaConsulta = bEjecutaConsulta;
            this.bEjecutaPdf = bEjecutaPdf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revisaXmlValidoSATPDFNoPasswordEfosResponse", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class revisaXmlValidoSATPDFNoPasswordEfosResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordEfosResponseReturn @return;
        
        public revisaXmlValidoSATPDFNoPasswordEfosResponse1()
        {
        }
        
        public revisaXmlValidoSATPDFNoPasswordEfosResponse1(GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordEfosResponseReturn @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revisaXmlValidoSATPDF", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class revisaXmlValidoSATPDF1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] xml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string claveTipoPdf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bRegresaXmlValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaConsulta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaPdf;
        
        public revisaXmlValidoSATPDF1()
        {
        }
        
        public revisaXmlValidoSATPDF1(byte[] xml, string usuario, string password, string claveTipoPdf, bool bEjecutaValidacion, bool bRegresaXmlValidacion, bool bEjecutaConsulta, bool bEjecutaPdf)
        {
            this.xml = xml;
            this.usuario = usuario;
            this.password = password;
            this.claveTipoPdf = claveTipoPdf;
            this.bEjecutaValidacion = bEjecutaValidacion;
            this.bRegresaXmlValidacion = bRegresaXmlValidacion;
            this.bEjecutaConsulta = bEjecutaConsulta;
            this.bEjecutaPdf = bEjecutaPdf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revisaXmlValidoSATPDFResponse", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class revisaXmlValidoSATPDFResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GeneraPdfBuzonE.revisaXmlValidoSATPDFResponseReturn @return;
        
        public revisaXmlValidoSATPDFResponse1()
        {
        }
        
        public revisaXmlValidoSATPDFResponse1(GeneraPdfBuzonE.revisaXmlValidoSATPDFResponseReturn @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revisaXmlValidoSATPDFEfos", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class revisaXmlValidoSATPDFEfos1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] xml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string claveTipoPdf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bRegresaXmlValidacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaConsulta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bEjecutaPdf;
        
        public revisaXmlValidoSATPDFEfos1()
        {
        }
        
        public revisaXmlValidoSATPDFEfos1(byte[] xml, string usuario, string password, string claveTipoPdf, bool bEjecutaValidacion, bool bRegresaXmlValidacion, bool bEjecutaConsulta, bool bEjecutaPdf)
        {
            this.xml = xml;
            this.usuario = usuario;
            this.password = password;
            this.claveTipoPdf = claveTipoPdf;
            this.bEjecutaValidacion = bEjecutaValidacion;
            this.bRegresaXmlValidacion = bRegresaXmlValidacion;
            this.bEjecutaConsulta = bEjecutaConsulta;
            this.bEjecutaPdf = bEjecutaPdf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revisaXmlValidoSATPDFEfosResponse", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class revisaXmlValidoSATPDFEfosResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GeneraPdfBuzonE.revisaXmlValidoSATPDFEfosResponseReturn @return;
        
        public revisaXmlValidoSATPDFEfosResponse1()
        {
        }
        
        public revisaXmlValidoSATPDFEfosResponse1(GeneraPdfBuzonE.revisaXmlValidoSATPDFEfosResponseReturn @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setAsyncBinnacle", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class setAsyncBinnacle1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.serviciosbuzone.buzone.com.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GeneraPdfBuzonE.asyncBinnacle arg0;
        
        public setAsyncBinnacle1()
        {
        }
        
        public setAsyncBinnacle1(GeneraPdfBuzonE.asyncBinnacle arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setAsyncBinnacleResponse", WrapperNamespace="http://webservices.serviciosbuzone.buzone.com.mx/", IsWrapped=true)]
    public partial class setAsyncBinnacleResponse1
    {
        
        public setAsyncBinnacleResponse1()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WsVerificaXmlRiChannel : GeneraPdfBuzonE.WsVerificaXmlRi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WsVerificaXmlRiClient : System.ServiceModel.ClientBase<GeneraPdfBuzonE.WsVerificaXmlRi>, GeneraPdfBuzonE.WsVerificaXmlRi
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsVerificaXmlRiClient() : 
                base(WsVerificaXmlRiClient.GetDefaultBinding(), WsVerificaXmlRiClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WsVerificaXmlRiPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsVerificaXmlRiClient(EndpointConfiguration endpointConfiguration) : 
                base(WsVerificaXmlRiClient.GetBindingForEndpoint(endpointConfiguration), WsVerificaXmlRiClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsVerificaXmlRiClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsVerificaXmlRiClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsVerificaXmlRiClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsVerificaXmlRiClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsVerificaXmlRiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task initAsync()
        {
            return base.Channel.initAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordResponse1> GeneraPdfBuzonE.WsVerificaXmlRi.revisaXmlValidoSATPDFNoPasswordAsync(GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPassword1 request)
        {
            return base.Channel.revisaXmlValidoSATPDFNoPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordResponse1> revisaXmlValidoSATPDFNoPasswordAsync(byte[] xml, int idUsuario, string claveTipoPdf, bool bEjecutaValidacion, bool bRegresaXmlValidacion, bool bEjecutaConsulta, bool bEjecutaPdf)
        {
            GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPassword1 inValue = new GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPassword1();
            inValue.xml = xml;
            inValue.idUsuario = idUsuario;
            inValue.claveTipoPdf = claveTipoPdf;
            inValue.bEjecutaValidacion = bEjecutaValidacion;
            inValue.bRegresaXmlValidacion = bRegresaXmlValidacion;
            inValue.bEjecutaConsulta = bEjecutaConsulta;
            inValue.bEjecutaPdf = bEjecutaPdf;
            return ((GeneraPdfBuzonE.WsVerificaXmlRi)(this)).revisaXmlValidoSATPDFNoPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordEfosResponse1> GeneraPdfBuzonE.WsVerificaXmlRi.revisaXmlValidoSATPDFNoPasswordEfosAsync(GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordEfos1 request)
        {
            return base.Channel.revisaXmlValidoSATPDFNoPasswordEfosAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordEfosResponse1> revisaXmlValidoSATPDFNoPasswordEfosAsync(byte[] xml, int idUsuario, string claveTipoPdf, bool bEjecutaValidacion, bool bRegresaXmlValidacion, bool bEjecutaConsulta, bool bEjecutaPdf)
        {
            GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordEfos1 inValue = new GeneraPdfBuzonE.revisaXmlValidoSATPDFNoPasswordEfos1();
            inValue.xml = xml;
            inValue.idUsuario = idUsuario;
            inValue.claveTipoPdf = claveTipoPdf;
            inValue.bEjecutaValidacion = bEjecutaValidacion;
            inValue.bRegresaXmlValidacion = bRegresaXmlValidacion;
            inValue.bEjecutaConsulta = bEjecutaConsulta;
            inValue.bEjecutaPdf = bEjecutaPdf;
            return ((GeneraPdfBuzonE.WsVerificaXmlRi)(this)).revisaXmlValidoSATPDFNoPasswordEfosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFResponse1> GeneraPdfBuzonE.WsVerificaXmlRi.revisaXmlValidoSATPDFAsync(GeneraPdfBuzonE.revisaXmlValidoSATPDF1 request)
        {
            return base.Channel.revisaXmlValidoSATPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFResponse1> revisaXmlValidoSATPDFAsync(byte[] xml, string usuario, string password, string claveTipoPdf, bool bEjecutaValidacion, bool bRegresaXmlValidacion, bool bEjecutaConsulta, bool bEjecutaPdf)
        {
            GeneraPdfBuzonE.revisaXmlValidoSATPDF1 inValue = new GeneraPdfBuzonE.revisaXmlValidoSATPDF1();
            inValue.xml = xml;
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.claveTipoPdf = claveTipoPdf;
            inValue.bEjecutaValidacion = bEjecutaValidacion;
            inValue.bRegresaXmlValidacion = bRegresaXmlValidacion;
            inValue.bEjecutaConsulta = bEjecutaConsulta;
            inValue.bEjecutaPdf = bEjecutaPdf;
            return ((GeneraPdfBuzonE.WsVerificaXmlRi)(this)).revisaXmlValidoSATPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFEfosResponse1> GeneraPdfBuzonE.WsVerificaXmlRi.revisaXmlValidoSATPDFEfosAsync(GeneraPdfBuzonE.revisaXmlValidoSATPDFEfos1 request)
        {
            return base.Channel.revisaXmlValidoSATPDFEfosAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeneraPdfBuzonE.revisaXmlValidoSATPDFEfosResponse1> revisaXmlValidoSATPDFEfosAsync(byte[] xml, string usuario, string password, string claveTipoPdf, bool bEjecutaValidacion, bool bRegresaXmlValidacion, bool bEjecutaConsulta, bool bEjecutaPdf)
        {
            GeneraPdfBuzonE.revisaXmlValidoSATPDFEfos1 inValue = new GeneraPdfBuzonE.revisaXmlValidoSATPDFEfos1();
            inValue.xml = xml;
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.claveTipoPdf = claveTipoPdf;
            inValue.bEjecutaValidacion = bEjecutaValidacion;
            inValue.bRegresaXmlValidacion = bRegresaXmlValidacion;
            inValue.bEjecutaConsulta = bEjecutaConsulta;
            inValue.bEjecutaPdf = bEjecutaPdf;
            return ((GeneraPdfBuzonE.WsVerificaXmlRi)(this)).revisaXmlValidoSATPDFEfosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeneraPdfBuzonE.setAsyncBinnacleResponse1> GeneraPdfBuzonE.WsVerificaXmlRi.setAsyncBinnacleAsync(GeneraPdfBuzonE.setAsyncBinnacle1 request)
        {
            return base.Channel.setAsyncBinnacleAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeneraPdfBuzonE.setAsyncBinnacleResponse1> setAsyncBinnacleAsync(GeneraPdfBuzonE.asyncBinnacle arg0)
        {
            GeneraPdfBuzonE.setAsyncBinnacle1 inValue = new GeneraPdfBuzonE.setAsyncBinnacle1();
            inValue.arg0 = arg0;
            return ((GeneraPdfBuzonE.WsVerificaXmlRi)(this)).setAsyncBinnacleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsVerificaXmlRiPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsVerificaXmlRiPort))
            {
                return new System.ServiceModel.EndpointAddress("https://serviciosweb.buzone.com.mx/ServiciosBuzone-Webservices/WsVerificaXmlRi");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WsVerificaXmlRiClient.GetBindingForEndpoint(EndpointConfiguration.WsVerificaXmlRiPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WsVerificaXmlRiClient.GetEndpointAddress(EndpointConfiguration.WsVerificaXmlRiPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WsVerificaXmlRiPort,
        }
    }
}
