//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceOne
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvoiceOne.ioTimbreCFDISoap")]
    public interface ioTimbreCFDISoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.ObtenerCFDIResponse> ObtenerCFDIAsync(InvoiceOne.ObtenerCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTFD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.ObtenerTFDResponse> ObtenerTFDAsync(InvoiceOne.ObtenerTFDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCFDIPrueba", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.ObtenerCFDIPruebaResponse> ObtenerCFDIPruebaAsync(InvoiceOne.ObtenerCFDIPruebaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTFDPrueba", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.ObtenerTFDPruebaResponse> ObtenerTFDPruebaAsync(InvoiceOne.ObtenerTFDPruebaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelaCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIResponse> cancelaCFDIAsync(InvoiceOne.cancelaCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelaCFDIPruebas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIPruebasResponse> cancelaCFDIPruebasAsync(InvoiceOne.cancelaCFDIPruebasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelaCFDI_PEM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.IOAcuseCancelacion> cancelaCFDI_PEMAsync(string nombreUsuario, string contraseña, string rfcEmisor, System.Guid[] listaUuid, string cerBase64, string keyPemBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtieneAcuseCancelacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.IOAcuseTimbradoCfdi> obtieneAcuseCancelacionAsync(string nombreUsuario, string contraseña, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtieneNumeroCertificadoPAC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> obtieneNumeroCertificadoPACAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtieneFecha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> obtieneFechaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/recuperaComprobanteXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.recuperaComprobanteXMLResponse> recuperaComprobanteXMLAsync(InvoiceOne.recuperaComprobanteXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCFDIconReferencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.obtenerCFDIconReferenciaResponse> obtenerCFDIconReferenciaAsync(InvoiceOne.obtenerCFDIconReferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerInfoIntegrador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.obtenerInfoIntegradorResponse> obtenerInfoIntegradorAsync(InvoiceOne.obtenerInfoIntegradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelaSAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.IOAcuseCancelacion> cancelaSATAsync(string usuario, string contrasena, string xmlPeticionSAT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelaSATPruebas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.IOAcuseCancelacion> cancelaSATPruebasAsync(string usuario, string contrasena, string xmlPeticionSAT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelaCFDIConsultaSAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.RespuestaCancelaCFDI> CancelaCFDIConsultaSATAsync(string Usuario, string Password, string RFCEmisor, string RFCReceptor, string Total, string UUID, string MotivoCancelacion, string FolioSustitucion, string pfxBase64, string pfxPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestCancelaCFDIConsultaSAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.RespuestaCancelaCFDI> TestCancelaCFDIConsultaSATAsync(string Usuario, string Password, string RFCEmisor, string RFCReceptor, string Total, string UUID, string MotivoCancelacion, string FolioSustitucion, string pfxBase64, string pfxPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelaCFDIv4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIv4Response> cancelaCFDIv4Async(InvoiceOne.cancelaCFDIv4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelaCFDIv4_Pruebas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIv4_PruebasResponse> cancelaCFDIv4_PruebasAsync(InvoiceOne.cancelaCFDIv4_PruebasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelaCFDIv4_PEM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InvoiceOne.IOAcuseCancelacion> cancelaCFDIv4_PEMAsync(string nombreUsuario, string contrasena, string rfcEmisor, InvoiceOne.UUIDaCancelar[] ListaUUIDsCancelar, string cerBase64, string keyPemBase64);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapHeaderAplicativoGratuito
    {
        
        private System.Guid id_TicketAplicativoGratuitoField;
        
        private System.Guid id_TokenField;
        
        private long fechaCreacionField;
        
        private long fechaExpiraField;
        
        private AppInfoCfdi infoCfdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id_TicketAplicativoGratuito
        {
            get
            {
                return this.id_TicketAplicativoGratuitoField;
            }
            set
            {
                this.id_TicketAplicativoGratuitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid Id_Token
        {
            get
            {
                return this.id_TokenField;
            }
            set
            {
                this.id_TokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long FechaCreacion
        {
            get
            {
                return this.fechaCreacionField;
            }
            set
            {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long FechaExpira
        {
            get
            {
                return this.fechaExpiraField;
            }
            set
            {
                this.fechaExpiraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public AppInfoCfdi InfoCfdi
        {
            get
            {
                return this.infoCfdiField;
            }
            set
            {
                this.infoCfdiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AppInfoCfdi
    {
        
        private System.Guid id_Num_EmisorField;
        
        private System.Nullable<System.Guid> id_Num_ReceptorField;
        
        private System.Nullable<System.Guid> id_UsuarioField;
        
        private System.Nullable<System.Guid> id_OficinaField;
        
        private string importeLetraField;
        
        private int id_TipoFormaPagoField;
        
        private System.Nullable<System.Guid> id_FolioField;
        
        private int id_TipoCFDIField;
        
        private int id_MonedaField;
        
        private bool bit_PagadaField;
        
        private System.Nullable<int> folioField;
        
        private string formaPagoTextoField;
        
        private string comentarioConceptoField;
        
        private string id_tickets_ListaField;
        
        private string id_tickets_HASHField;
        
        private string numeroClienteField;
        
        private string numeroOrdenField;
        
        private string numeroProveedorField;
        
        private string nombreAgenteVentasField;
        
        private string nombreCompradorField;
        
        private string nombreComercialField;
        
        private string observacionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id_Num_Emisor
        {
            get
            {
                return this.id_Num_EmisorField;
            }
            set
            {
                this.id_Num_EmisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.Guid> Id_Num_Receptor
        {
            get
            {
                return this.id_Num_ReceptorField;
            }
            set
            {
                this.id_Num_ReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.Guid> Id_Usuario
        {
            get
            {
                return this.id_UsuarioField;
            }
            set
            {
                this.id_UsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.Guid> Id_Oficina
        {
            get
            {
                return this.id_OficinaField;
            }
            set
            {
                this.id_OficinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ImporteLetra
        {
            get
            {
                return this.importeLetraField;
            }
            set
            {
                this.importeLetraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Id_TipoFormaPago
        {
            get
            {
                return this.id_TipoFormaPagoField;
            }
            set
            {
                this.id_TipoFormaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.Guid> Id_Folio
        {
            get
            {
                return this.id_FolioField;
            }
            set
            {
                this.id_FolioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Id_TipoCFDI
        {
            get
            {
                return this.id_TipoCFDIField;
            }
            set
            {
                this.id_TipoCFDIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Id_Moneda
        {
            get
            {
                return this.id_MonedaField;
            }
            set
            {
                this.id_MonedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Bit_Pagada
        {
            get
            {
                return this.bit_PagadaField;
            }
            set
            {
                this.bit_PagadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> Folio
        {
            get
            {
                return this.folioField;
            }
            set
            {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FormaPagoTexto
        {
            get
            {
                return this.formaPagoTextoField;
            }
            set
            {
                this.formaPagoTextoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ComentarioConcepto
        {
            get
            {
                return this.comentarioConceptoField;
            }
            set
            {
                this.comentarioConceptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Id_tickets_Lista
        {
            get
            {
                return this.id_tickets_ListaField;
            }
            set
            {
                this.id_tickets_ListaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Id_tickets_HASH
        {
            get
            {
                return this.id_tickets_HASHField;
            }
            set
            {
                this.id_tickets_HASHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string NumeroCliente
        {
            get
            {
                return this.numeroClienteField;
            }
            set
            {
                this.numeroClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string NumeroOrden
        {
            get
            {
                return this.numeroOrdenField;
            }
            set
            {
                this.numeroOrdenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NumeroProveedor
        {
            get
            {
                return this.numeroProveedorField;
            }
            set
            {
                this.numeroProveedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string NombreAgenteVentas
        {
            get
            {
                return this.nombreAgenteVentasField;
            }
            set
            {
                this.nombreAgenteVentasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string NombreComprador
        {
            get
            {
                return this.nombreCompradorField;
            }
            set
            {
                this.nombreCompradorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string NombreComercial
        {
            get
            {
                return this.nombreComercialField;
            }
            set
            {
                this.nombreComercialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UUIDaCancelar
    {
        
        private System.Guid uUIDField;
        
        private string motivoCancelacionField;
        
        private System.Nullable<System.Guid> folioSustitucionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MotivoCancelacion
        {
            get
            {
                return this.motivoCancelacionField;
            }
            set
            {
                this.motivoCancelacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.Guid> FolioSustitucion
        {
            get
            {
                return this.folioSustitucionField;
            }
            set
            {
                this.folioSustitucionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaCancelaCFDIFolio
    {
        
        private string uUIDField;
        
        private string estatusUUIDField;
        
        private string codigoEstatusField;
        
        private string esCancelableField;
        
        private string estadoField;
        
        private string estatusCancelacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EstatusUUID
        {
            get
            {
                return this.estatusUUIDField;
            }
            set
            {
                this.estatusUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoEstatus
        {
            get
            {
                return this.codigoEstatusField;
            }
            set
            {
                this.codigoEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EsCancelable
        {
            get
            {
                return this.esCancelableField;
            }
            set
            {
                this.esCancelableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EstatusCancelacion
        {
            get
            {
                return this.estatusCancelacionField;
            }
            set
            {
                this.estatusCancelacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaCancelaCFDI
    {
        
        private string codEstatusField;
        
        private System.DateTime fechaField;
        
        private string rfcEmisorField;
        
        private RespuestaCancelaCFDIFolio[] foliosField;
        
        private string acuseXMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CodEstatus
        {
            get
            {
                return this.codEstatusField;
            }
            set
            {
                this.codEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RfcEmisor
        {
            get
            {
                return this.rfcEmisorField;
            }
            set
            {
                this.rfcEmisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public RespuestaCancelaCFDIFolio[] Folios
        {
            get
            {
                return this.foliosField;
            }
            set
            {
                this.foliosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AcuseXML
        {
            get
            {
                return this.acuseXMLField;
            }
            set
            {
                this.acuseXMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoIntegrador
    {
        
        private int produccion_FoliosTotalField;
        
        private int produccion_FoliosConsumidosField;
        
        private int pruebas_FoliosTotalField;
        
        private int pruebas_FoliosConsumidosField;
        
        private string fechaConsultaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Produccion_FoliosTotal
        {
            get
            {
                return this.produccion_FoliosTotalField;
            }
            set
            {
                this.produccion_FoliosTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Produccion_FoliosConsumidos
        {
            get
            {
                return this.produccion_FoliosConsumidosField;
            }
            set
            {
                this.produccion_FoliosConsumidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Pruebas_FoliosTotal
        {
            get
            {
                return this.pruebas_FoliosTotalField;
            }
            set
            {
                this.pruebas_FoliosTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Pruebas_FoliosConsumidos
        {
            get
            {
                return this.pruebas_FoliosConsumidosField;
            }
            set
            {
                this.pruebas_FoliosConsumidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FechaConsulta
        {
            get
            {
                return this.fechaConsultaField;
            }
            set
            {
                this.fechaConsultaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ComprobanteCancelado
    {
        
        private System.Guid uUIDField;
        
        private EnumCancelado canceladoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EnumCancelado Cancelado
        {
            get
            {
                return this.canceladoField;
            }
            set
            {
                this.canceladoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumCancelado
    {
        
        /// <remarks/>
        NoValido,
        
        /// <remarks/>
        Cancelado,
        
        /// <remarks/>
        PreviamenteCancelado,
        
        /// <remarks/>
        NoCorrespondeAlEmisor,
        
        /// <remarks/>
        NoAplicableParaCancelacion,
        
        /// <remarks/>
        UUIDNoExiste,
        
        /// <remarks/>
        NoIdentificado206,
        
        /// <remarks/>
        NoIdentificado207,
        
        /// <remarks/>
        NoIdentificado208,
        
        /// <remarks/>
        NoIdentificado209,
        
        /// <remarks/>
        NoIdentificado210,
        
        /// <remarks/>
        NoVerificado,
        
        /// <remarks/>
        UsuarioNoExiste,
        
        /// <remarks/>
        NoCumpleConEstandarXSD,
        
        /// <remarks/>
        SelloDelEmisorInvalido,
        
        /// <remarks/>
        CSDEmisorNoCorrespondeRFC,
        
        /// <remarks/>
        CSDEmisorRevocado,
        
        /// <remarks/>
        FechaEmisionFueraDeVigencia,
        
        /// <remarks/>
        CSDesFIEL,
        
        /// <remarks/>
        TimbrePrevio,
        
        /// <remarks/>
        CSDNoValidoPorSAT,
        
        /// <remarks/>
        FechaMayor72Horas,
        
        /// <remarks/>
        RFCSinValidesDeObligacion,
        
        /// <remarks/>
        FechaInferiorAEnero,
        
        /// <remarks/>
        RetencionCancelado,
        
        /// <remarks/>
        RetencionPreviamenteCancelado,
        
        /// <remarks/>
        RetencionNoCorrespondeEmisor,
        
        /// <remarks/>
        RetencionNoExiste,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IOAcuseCancelacion
    {
        
        private string xmlAcuseField;
        
        private ComprobanteCancelado[] comprobantesCanceladoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string XmlAcuse
        {
            get
            {
                return this.xmlAcuseField;
            }
            set
            {
                this.xmlAcuseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ComprobanteCancelado[] ComprobantesCancelado
        {
            get
            {
                return this.comprobantesCanceladoField;
            }
            set
            {
                this.comprobantesCanceladoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IOAcuseTimbradoCfdi
    {
        
        private string xmlField;
        
        private string xmlAcuseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string XmlAcuse
        {
            get
            {
                return this.xmlAcuseField;
            }
            set
            {
                this.xmlAcuseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerCFDI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerCFDIRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlComprobante;
        
        public ObtenerCFDIRequest()
        {
        }
        
        public ObtenerCFDIRequest(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contraseña, string xmlComprobante)
        {
            this.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            this.nombreUsuario = nombreUsuario;
            this.contraseña = contraseña;
            this.xmlComprobante = xmlComprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerCFDIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerCFDIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseTimbradoCfdi ObtenerCFDIResult;
        
        public ObtenerCFDIResponse()
        {
        }
        
        public ObtenerCFDIResponse(InvoiceOne.IOAcuseTimbradoCfdi ObtenerCFDIResult)
        {
            this.ObtenerCFDIResult = ObtenerCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTFD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerTFDRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlComprobante;
        
        public ObtenerTFDRequest()
        {
        }
        
        public ObtenerTFDRequest(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contraseña, string xmlComprobante)
        {
            this.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            this.nombreUsuario = nombreUsuario;
            this.contraseña = contraseña;
            this.xmlComprobante = xmlComprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTFDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerTFDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseTimbradoCfdi ObtenerTFDResult;
        
        public ObtenerTFDResponse()
        {
        }
        
        public ObtenerTFDResponse(InvoiceOne.IOAcuseTimbradoCfdi ObtenerTFDResult)
        {
            this.ObtenerTFDResult = ObtenerTFDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerCFDIPrueba", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerCFDIPruebaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlComprobante;
        
        public ObtenerCFDIPruebaRequest()
        {
        }
        
        public ObtenerCFDIPruebaRequest(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string usuario, string contraseña, string xmlComprobante)
        {
            this.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            this.usuario = usuario;
            this.contraseña = contraseña;
            this.xmlComprobante = xmlComprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerCFDIPruebaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerCFDIPruebaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseTimbradoCfdi ObtenerCFDIPruebaResult;
        
        public ObtenerCFDIPruebaResponse()
        {
        }
        
        public ObtenerCFDIPruebaResponse(InvoiceOne.IOAcuseTimbradoCfdi ObtenerCFDIPruebaResult)
        {
            this.ObtenerCFDIPruebaResult = ObtenerCFDIPruebaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTFDPrueba", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerTFDPruebaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlComprobante;
        
        public ObtenerTFDPruebaRequest()
        {
        }
        
        public ObtenerTFDPruebaRequest(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string usuario, string contraseña, string xmlComprobante)
        {
            this.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            this.usuario = usuario;
            this.contraseña = contraseña;
            this.xmlComprobante = xmlComprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTFDPruebaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerTFDPruebaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseTimbradoCfdi ObtenerTFDPruebaResult;
        
        public ObtenerTFDPruebaResponse()
        {
        }
        
        public ObtenerTFDPruebaResponse(InvoiceOne.IOAcuseTimbradoCfdi ObtenerTFDPruebaResult)
        {
            this.ObtenerTFDPruebaResult = ObtenerTFDPruebaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class cancelaCFDIRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Guid[] listaUuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pfxBase64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string contrasenaPfx;
        
        public cancelaCFDIRequest()
        {
        }
        
        public cancelaCFDIRequest(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contraseña, string rfcEmisor, System.Guid[] listaUuid, string pfxBase64, string contrasenaPfx)
        {
            this.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            this.nombreUsuario = nombreUsuario;
            this.contraseña = contraseña;
            this.rfcEmisor = rfcEmisor;
            this.listaUuid = listaUuid;
            this.pfxBase64 = pfxBase64;
            this.contrasenaPfx = contrasenaPfx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class cancelaCFDIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseCancelacion cancelaCFDIResult;
        
        public cancelaCFDIResponse()
        {
        }
        
        public cancelaCFDIResponse(InvoiceOne.IOAcuseCancelacion cancelaCFDIResult)
        {
            this.cancelaCFDIResult = cancelaCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDIPruebas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class cancelaCFDIPruebasRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contraseña;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Guid[] listaUuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pfxBase64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string contrasenaPfx;
        
        public cancelaCFDIPruebasRequest()
        {
        }
        
        public cancelaCFDIPruebasRequest(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contraseña, string rfcEmisor, System.Guid[] listaUuid, string pfxBase64, string contrasenaPfx)
        {
            this.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            this.nombreUsuario = nombreUsuario;
            this.contraseña = contraseña;
            this.rfcEmisor = rfcEmisor;
            this.listaUuid = listaUuid;
            this.pfxBase64 = pfxBase64;
            this.contrasenaPfx = contrasenaPfx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDIPruebasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class cancelaCFDIPruebasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseCancelacion cancelaCFDIPruebasResult;
        
        public cancelaCFDIPruebasResponse()
        {
        }
        
        public cancelaCFDIPruebasResponse(InvoiceOne.IOAcuseCancelacion cancelaCFDIPruebasResult)
        {
            this.cancelaCFDIPruebasResult = cancelaCFDIPruebasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaComprobanteXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class recuperaComprobanteXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contrasena;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> id_cliente;
        
        public recuperaComprobanteXMLRequest()
        {
        }
        
        public recuperaComprobanteXMLRequest(string nombreUsuario, string contrasena, string xml, string referencia, System.Nullable<System.Guid> id_cliente)
        {
            this.nombreUsuario = nombreUsuario;
            this.contrasena = contrasena;
            this.xml = xml;
            this.referencia = referencia;
            this.id_cliente = id_cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaComprobanteXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class recuperaComprobanteXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseTimbradoCfdi recuperaComprobanteXMLResult;
        
        public recuperaComprobanteXMLResponse()
        {
        }
        
        public recuperaComprobanteXMLResponse(InvoiceOne.IOAcuseTimbradoCfdi recuperaComprobanteXMLResult)
        {
            this.recuperaComprobanteXMLResult = recuperaComprobanteXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCFDIconReferencia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerCFDIconReferenciaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contrasena;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlComprobante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> id_cliente;
        
        public obtenerCFDIconReferenciaRequest()
        {
        }
        
        public obtenerCFDIconReferenciaRequest(string nombreUsuario, string contrasena, string xmlComprobante, string referencia, System.Nullable<System.Guid> id_cliente)
        {
            this.nombreUsuario = nombreUsuario;
            this.contrasena = contrasena;
            this.xmlComprobante = xmlComprobante;
            this.referencia = referencia;
            this.id_cliente = id_cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCFDIconReferenciaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerCFDIconReferenciaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseTimbradoCfdi obtenerCFDIconReferenciaResult;
        
        public obtenerCFDIconReferenciaResponse()
        {
        }
        
        public obtenerCFDIconReferenciaResponse(InvoiceOne.IOAcuseTimbradoCfdi obtenerCFDIconReferenciaResult)
        {
            this.obtenerCFDIconReferenciaResult = obtenerCFDIconReferenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerInfoIntegrador", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerInfoIntegradorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contrasena;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> Id_Cliente_Integrador;
        
        public obtenerInfoIntegradorRequest()
        {
        }
        
        public obtenerInfoIntegradorRequest(string nombreUsuario, string contrasena, System.Nullable<System.Guid> Id_Cliente_Integrador)
        {
            this.nombreUsuario = nombreUsuario;
            this.contrasena = contrasena;
            this.Id_Cliente_Integrador = Id_Cliente_Integrador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerInfoIntegradorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerInfoIntegradorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.InfoIntegrador obtenerInfoIntegradorResult;
        
        public obtenerInfoIntegradorResponse()
        {
        }
        
        public obtenerInfoIntegradorResponse(InvoiceOne.InfoIntegrador obtenerInfoIntegradorResult)
        {
            this.obtenerInfoIntegradorResult = obtenerInfoIntegradorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDIv4", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class cancelaCFDIv4Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contrasena;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public InvoiceOne.UUIDaCancelar[] ListaUUIDsCancelar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pfxBase64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string contrasenaPfx;
        
        public cancelaCFDIv4Request()
        {
        }
        
        public cancelaCFDIv4Request(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contrasena, string rfcEmisor, InvoiceOne.UUIDaCancelar[] ListaUUIDsCancelar, string pfxBase64, string contrasenaPfx)
        {
            this.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            this.nombreUsuario = nombreUsuario;
            this.contrasena = contrasena;
            this.rfcEmisor = rfcEmisor;
            this.ListaUUIDsCancelar = ListaUUIDsCancelar;
            this.pfxBase64 = pfxBase64;
            this.contrasenaPfx = contrasenaPfx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDIv4Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class cancelaCFDIv4Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseCancelacion cancelaCFDIv4Result;
        
        public cancelaCFDIv4Response()
        {
        }
        
        public cancelaCFDIv4Response(InvoiceOne.IOAcuseCancelacion cancelaCFDIv4Result)
        {
            this.cancelaCFDIv4Result = cancelaCFDIv4Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDIv4_Pruebas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class cancelaCFDIv4_PruebasRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contrasena;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public InvoiceOne.UUIDaCancelar[] ListaUUIDsCancelar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pfxBase64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string contrasenaPfx;
        
        public cancelaCFDIv4_PruebasRequest()
        {
        }
        
        public cancelaCFDIv4_PruebasRequest(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contrasena, string rfcEmisor, InvoiceOne.UUIDaCancelar[] ListaUUIDsCancelar, string pfxBase64, string contrasenaPfx)
        {
            this.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            this.nombreUsuario = nombreUsuario;
            this.contrasena = contrasena;
            this.rfcEmisor = rfcEmisor;
            this.ListaUUIDsCancelar = ListaUUIDsCancelar;
            this.pfxBase64 = pfxBase64;
            this.contrasenaPfx = contrasenaPfx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDIv4_PruebasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class cancelaCFDIv4_PruebasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public InvoiceOne.IOAcuseCancelacion cancelaCFDIv4_PruebasResult;
        
        public cancelaCFDIv4_PruebasResponse()
        {
        }
        
        public cancelaCFDIv4_PruebasResponse(InvoiceOne.IOAcuseCancelacion cancelaCFDIv4_PruebasResult)
        {
            this.cancelaCFDIv4_PruebasResult = cancelaCFDIv4_PruebasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ioTimbreCFDISoapChannel : InvoiceOne.ioTimbreCFDISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ioTimbreCFDISoapClient : System.ServiceModel.ClientBase<InvoiceOne.ioTimbreCFDISoap>, InvoiceOne.ioTimbreCFDISoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ioTimbreCFDISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ioTimbreCFDISoapClient.GetBindingForEndpoint(endpointConfiguration), ioTimbreCFDISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ioTimbreCFDISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ioTimbreCFDISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ioTimbreCFDISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ioTimbreCFDISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ioTimbreCFDISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.ObtenerCFDIResponse> InvoiceOne.ioTimbreCFDISoap.ObtenerCFDIAsync(InvoiceOne.ObtenerCFDIRequest request)
        {
            return base.Channel.ObtenerCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.ObtenerCFDIResponse> ObtenerCFDIAsync(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contraseña, string xmlComprobante)
        {
            InvoiceOne.ObtenerCFDIRequest inValue = new InvoiceOne.ObtenerCFDIRequest();
            inValue.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contraseña = contraseña;
            inValue.xmlComprobante = xmlComprobante;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).ObtenerCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.ObtenerTFDResponse> InvoiceOne.ioTimbreCFDISoap.ObtenerTFDAsync(InvoiceOne.ObtenerTFDRequest request)
        {
            return base.Channel.ObtenerTFDAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.ObtenerTFDResponse> ObtenerTFDAsync(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contraseña, string xmlComprobante)
        {
            InvoiceOne.ObtenerTFDRequest inValue = new InvoiceOne.ObtenerTFDRequest();
            inValue.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contraseña = contraseña;
            inValue.xmlComprobante = xmlComprobante;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).ObtenerTFDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.ObtenerCFDIPruebaResponse> InvoiceOne.ioTimbreCFDISoap.ObtenerCFDIPruebaAsync(InvoiceOne.ObtenerCFDIPruebaRequest request)
        {
            return base.Channel.ObtenerCFDIPruebaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.ObtenerCFDIPruebaResponse> ObtenerCFDIPruebaAsync(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string usuario, string contraseña, string xmlComprobante)
        {
            InvoiceOne.ObtenerCFDIPruebaRequest inValue = new InvoiceOne.ObtenerCFDIPruebaRequest();
            inValue.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            inValue.usuario = usuario;
            inValue.contraseña = contraseña;
            inValue.xmlComprobante = xmlComprobante;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).ObtenerCFDIPruebaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.ObtenerTFDPruebaResponse> InvoiceOne.ioTimbreCFDISoap.ObtenerTFDPruebaAsync(InvoiceOne.ObtenerTFDPruebaRequest request)
        {
            return base.Channel.ObtenerTFDPruebaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.ObtenerTFDPruebaResponse> ObtenerTFDPruebaAsync(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string usuario, string contraseña, string xmlComprobante)
        {
            InvoiceOne.ObtenerTFDPruebaRequest inValue = new InvoiceOne.ObtenerTFDPruebaRequest();
            inValue.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            inValue.usuario = usuario;
            inValue.contraseña = contraseña;
            inValue.xmlComprobante = xmlComprobante;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).ObtenerTFDPruebaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIResponse> InvoiceOne.ioTimbreCFDISoap.cancelaCFDIAsync(InvoiceOne.cancelaCFDIRequest request)
        {
            return base.Channel.cancelaCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIResponse> cancelaCFDIAsync(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contraseña, string rfcEmisor, System.Guid[] listaUuid, string pfxBase64, string contrasenaPfx)
        {
            InvoiceOne.cancelaCFDIRequest inValue = new InvoiceOne.cancelaCFDIRequest();
            inValue.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contraseña = contraseña;
            inValue.rfcEmisor = rfcEmisor;
            inValue.listaUuid = listaUuid;
            inValue.pfxBase64 = pfxBase64;
            inValue.contrasenaPfx = contrasenaPfx;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).cancelaCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIPruebasResponse> InvoiceOne.ioTimbreCFDISoap.cancelaCFDIPruebasAsync(InvoiceOne.cancelaCFDIPruebasRequest request)
        {
            return base.Channel.cancelaCFDIPruebasAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIPruebasResponse> cancelaCFDIPruebasAsync(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contraseña, string rfcEmisor, System.Guid[] listaUuid, string pfxBase64, string contrasenaPfx)
        {
            InvoiceOne.cancelaCFDIPruebasRequest inValue = new InvoiceOne.cancelaCFDIPruebasRequest();
            inValue.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contraseña = contraseña;
            inValue.rfcEmisor = rfcEmisor;
            inValue.listaUuid = listaUuid;
            inValue.pfxBase64 = pfxBase64;
            inValue.contrasenaPfx = contrasenaPfx;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).cancelaCFDIPruebasAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.IOAcuseCancelacion> cancelaCFDI_PEMAsync(string nombreUsuario, string contraseña, string rfcEmisor, System.Guid[] listaUuid, string cerBase64, string keyPemBase64)
        {
            return base.Channel.cancelaCFDI_PEMAsync(nombreUsuario, contraseña, rfcEmisor, listaUuid, cerBase64, keyPemBase64);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.IOAcuseTimbradoCfdi> obtieneAcuseCancelacionAsync(string nombreUsuario, string contraseña, string uuid)
        {
            return base.Channel.obtieneAcuseCancelacionAsync(nombreUsuario, contraseña, uuid);
        }
        
        public System.Threading.Tasks.Task<string> obtieneNumeroCertificadoPACAsync()
        {
            return base.Channel.obtieneNumeroCertificadoPACAsync();
        }
        
        public System.Threading.Tasks.Task<string> obtieneFechaAsync()
        {
            return base.Channel.obtieneFechaAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.recuperaComprobanteXMLResponse> InvoiceOne.ioTimbreCFDISoap.recuperaComprobanteXMLAsync(InvoiceOne.recuperaComprobanteXMLRequest request)
        {
            return base.Channel.recuperaComprobanteXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.recuperaComprobanteXMLResponse> recuperaComprobanteXMLAsync(string nombreUsuario, string contrasena, string xml, string referencia, System.Nullable<System.Guid> id_cliente)
        {
            InvoiceOne.recuperaComprobanteXMLRequest inValue = new InvoiceOne.recuperaComprobanteXMLRequest();
            inValue.nombreUsuario = nombreUsuario;
            inValue.contrasena = contrasena;
            inValue.xml = xml;
            inValue.referencia = referencia;
            inValue.id_cliente = id_cliente;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).recuperaComprobanteXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.obtenerCFDIconReferenciaResponse> InvoiceOne.ioTimbreCFDISoap.obtenerCFDIconReferenciaAsync(InvoiceOne.obtenerCFDIconReferenciaRequest request)
        {
            return base.Channel.obtenerCFDIconReferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.obtenerCFDIconReferenciaResponse> obtenerCFDIconReferenciaAsync(string nombreUsuario, string contrasena, string xmlComprobante, string referencia, System.Nullable<System.Guid> id_cliente)
        {
            InvoiceOne.obtenerCFDIconReferenciaRequest inValue = new InvoiceOne.obtenerCFDIconReferenciaRequest();
            inValue.nombreUsuario = nombreUsuario;
            inValue.contrasena = contrasena;
            inValue.xmlComprobante = xmlComprobante;
            inValue.referencia = referencia;
            inValue.id_cliente = id_cliente;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).obtenerCFDIconReferenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.obtenerInfoIntegradorResponse> InvoiceOne.ioTimbreCFDISoap.obtenerInfoIntegradorAsync(InvoiceOne.obtenerInfoIntegradorRequest request)
        {
            return base.Channel.obtenerInfoIntegradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.obtenerInfoIntegradorResponse> obtenerInfoIntegradorAsync(string nombreUsuario, string contrasena, System.Nullable<System.Guid> Id_Cliente_Integrador)
        {
            InvoiceOne.obtenerInfoIntegradorRequest inValue = new InvoiceOne.obtenerInfoIntegradorRequest();
            inValue.nombreUsuario = nombreUsuario;
            inValue.contrasena = contrasena;
            inValue.Id_Cliente_Integrador = Id_Cliente_Integrador;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).obtenerInfoIntegradorAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.IOAcuseCancelacion> cancelaSATAsync(string usuario, string contrasena, string xmlPeticionSAT)
        {
            return base.Channel.cancelaSATAsync(usuario, contrasena, xmlPeticionSAT);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.IOAcuseCancelacion> cancelaSATPruebasAsync(string usuario, string contrasena, string xmlPeticionSAT)
        {
            return base.Channel.cancelaSATPruebasAsync(usuario, contrasena, xmlPeticionSAT);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.RespuestaCancelaCFDI> CancelaCFDIConsultaSATAsync(string Usuario, string Password, string RFCEmisor, string RFCReceptor, string Total, string UUID, string MotivoCancelacion, string FolioSustitucion, string pfxBase64, string pfxPassword)
        {
            return base.Channel.CancelaCFDIConsultaSATAsync(Usuario, Password, RFCEmisor, RFCReceptor, Total, UUID, MotivoCancelacion, FolioSustitucion, pfxBase64, pfxPassword);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.RespuestaCancelaCFDI> TestCancelaCFDIConsultaSATAsync(string Usuario, string Password, string RFCEmisor, string RFCReceptor, string Total, string UUID, string MotivoCancelacion, string FolioSustitucion, string pfxBase64, string pfxPassword)
        {
            return base.Channel.TestCancelaCFDIConsultaSATAsync(Usuario, Password, RFCEmisor, RFCReceptor, Total, UUID, MotivoCancelacion, FolioSustitucion, pfxBase64, pfxPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIv4Response> InvoiceOne.ioTimbreCFDISoap.cancelaCFDIv4Async(InvoiceOne.cancelaCFDIv4Request request)
        {
            return base.Channel.cancelaCFDIv4Async(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIv4Response> cancelaCFDIv4Async(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contrasena, string rfcEmisor, InvoiceOne.UUIDaCancelar[] ListaUUIDsCancelar, string pfxBase64, string contrasenaPfx)
        {
            InvoiceOne.cancelaCFDIv4Request inValue = new InvoiceOne.cancelaCFDIv4Request();
            inValue.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contrasena = contrasena;
            inValue.rfcEmisor = rfcEmisor;
            inValue.ListaUUIDsCancelar = ListaUUIDsCancelar;
            inValue.pfxBase64 = pfxBase64;
            inValue.contrasenaPfx = contrasenaPfx;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).cancelaCFDIv4Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIv4_PruebasResponse> InvoiceOne.ioTimbreCFDISoap.cancelaCFDIv4_PruebasAsync(InvoiceOne.cancelaCFDIv4_PruebasRequest request)
        {
            return base.Channel.cancelaCFDIv4_PruebasAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.cancelaCFDIv4_PruebasResponse> cancelaCFDIv4_PruebasAsync(InvoiceOne.SoapHeaderAplicativoGratuito SoapHeaderAplicativoGratuito, string nombreUsuario, string contrasena, string rfcEmisor, InvoiceOne.UUIDaCancelar[] ListaUUIDsCancelar, string pfxBase64, string contrasenaPfx)
        {
            InvoiceOne.cancelaCFDIv4_PruebasRequest inValue = new InvoiceOne.cancelaCFDIv4_PruebasRequest();
            inValue.SoapHeaderAplicativoGratuito = SoapHeaderAplicativoGratuito;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contrasena = contrasena;
            inValue.rfcEmisor = rfcEmisor;
            inValue.ListaUUIDsCancelar = ListaUUIDsCancelar;
            inValue.pfxBase64 = pfxBase64;
            inValue.contrasenaPfx = contrasenaPfx;
            return ((InvoiceOne.ioTimbreCFDISoap)(this)).cancelaCFDIv4_PruebasAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<InvoiceOne.IOAcuseCancelacion> cancelaCFDIv4_PEMAsync(string nombreUsuario, string contrasena, string rfcEmisor, InvoiceOne.UUIDaCancelar[] ListaUUIDsCancelar, string cerBase64, string keyPemBase64)
        {
            return base.Channel.cancelaCFDIv4_PEMAsync(nombreUsuario, contrasena, rfcEmisor, ListaUUIDsCancelar, cerBase64, keyPemBase64);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ioTimbreCFDISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ioTimbreCFDISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ioTimbreCFDISoap))
            {
                return new System.ServiceModel.EndpointAddress("https://invoiceone.mx/TimbreCFDI/ioTimbreCFDI.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ioTimbreCFDISoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://invoiceone.mx/TimbreCFDI/ioTimbreCFDI.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ioTimbreCFDISoap,
            
            ioTimbreCFDISoap12,
        }
    }
}
